<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menu = [
            [
                'menu' => 'Dashboard',
                'link' => 'dashboard',
                'icon' => 'category',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 1,
                'dokter' => 1,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 1,
                'apoteker' => 1,
                'kasir' => 1,
                'perawat' => 1
            ],
            [
                'menu' => 'divider',
                'link' => '#',
                'icon' => null,
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 1,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 1,
                'apoteker' => 1,
                'kasir' => 1,
                'perawat' => 1
            ],
            [
                'menu' => 'Pendaftaran',
                'link' => '#',
                'icon' => 'notepad-edit',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 1,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 0,
                'submenu' => [
                    [
                        'menu' => 'Pendaftaran Pasien',
                        'link' => 'pendaftaran/pendaftaran-pasien',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 1,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'List Pendaftaran',
                        'link' => 'pendaftaran/list-pendaftaran',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 1,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Antrian Online',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 1,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                ],
            ],
            [
                'menu' => 'List Pasien',
                'link' => '#',
                'icon' => 'user',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 1,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 1,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 1,
                'submenu' => [
                    [
                        'menu' => 'Pasien IGD',
                        'link' => 'list-pasien/pasien-igd',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 1,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 1,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 1
                    ],
                    [
                        'menu' => 'Pasien Rawat Inap',
                        'link' => 'list-pasien/pasien-rawat-inap',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 1,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 1,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 1
                    ],
                    [
                        'menu' => 'Riwayat',
                        'link' => 'list-pasien/riwayat',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 1,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 1,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Kartu Pasien',
                        'link' => 'list-pasien/kartu-pasien',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 1,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Surat Keterangan',
                        'link' => 'list-pasien/surat-keterangan-kesehatan',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 1,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 1,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 1
                    ],
                ],
            ],
            [
                'menu' => 'Poliklinik',
                'link' => 'poliklinik',
                'icon' => 'home-2',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 1,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 1
            ],
            [
                'menu' => 'Management Kamar',
                'link' => 'management-kamar',
                'icon' => 'home-1',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 1,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 1
            ],
            [
                'menu' => 'Kehamilan',
                'link' => '#',
                'icon' => 'lovely',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 0,
                'submenu' => [
                    [
                        'menu' => 'Yoga',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Baby SPA',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Hypnobirth',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Perkiraan Kelahiran',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                ],
            ],
            [
                'menu' => 'BPJS',
                'link' => '#',
                'icon' => 'medal-star',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 0,
                'submenu' => [
                    [
                        'menu' => 'Riwayat Peserta BPJS',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Cetak Rujukan BPJS',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                ],
            ],
            [
                'menu' => 'Retail',
                'link' => '#',
                'icon' => 'shop',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 0,
                'submenu' => [
                    [
                        'menu' => 'Data Retail',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Ambulance',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                ],
            ],
            [
                'menu' => 'Kasir',
                'link' => '#',
                'icon' => 'monitor-mobile',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 1,
                'perawat' => 0
            ],
            [
                'menu' => 'divider',
                'link' => '#',
                'icon' => null,
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 0
            ],
            [
                'menu' => 'Apotek',
                'link' => 'apotek',
                'icon' => 'home',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 1,
                'kasir' => 0,
                'perawat' => 1
            ],
            [
                'menu' => 'Farmasi',
                'link' => '#',
                'icon' => 'home-3',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 1,
                'kasir' => 0,
                'perawat' => 0
            ],
            [
                'menu' => 'Obat Lock',
                'link' => '#',
                'icon' => 'information',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 1,
                'kasir' => 0,
                'perawat' => 0
            ],
            [
                'menu' => 'divider',
                'link' => '#',
                'icon' => null,
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 0
            ],
            [
                'menu' => 'Master Data',
                'link' => '#',
                'icon' => 'abstract-26',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 1,
                'kasir' => 0,
                'perawat' => 0,
                'submenu' => [
                    [
                        'menu' => 'Faskes',
                        'link' => 'master-data/faskes',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Poli',
                        'link' => 'master-data/poli',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Tindakan',
                        'link' => 'master-data/tindakan',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Tindakan Kategori',
                        'link' => 'master-data/tindakan-kategori',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Laborat',
                        'link' => 'master-data/laborat',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Laborat Kategori',
                        'link' => 'master-data/laborat-kategori',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Pegawai',
                        'link' => 'master-data/pegawai',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Pengguna',
                        'link' => 'master-data/pengguna',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Jadwal Poli',
                        'link' => 'master-data/jadwal-poli',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Diagnosa',
                        'link' => 'master-data/diagnosa',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Petugas Poli',
                        'link' => 'master-data/petugas-poli',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Kamar Rawat Inap',
                        'link' => 'master-data/kamar-rawat-inap',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Role',
                        'link' => 'master-data/role',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Data Obat',
                        'link' => 'master-data/data-obat',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 1,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Satuan Obat',
                        'link' => 'master-data/satuan-obat',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Klasifikasi Obat',
                        'link' => 'master-data/klasifikasi-obat',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Jenis Pembayaran',
                        'link' => 'master-data/jenis-pembayaran',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Data Spesialis',
                        'link' => 'master-data/data-spesialis',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 0,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                ],
            ],
            [
                'menu' => 'Laporan',
                'link' => '#',
                'icon' => 'some-files',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 0,
                'submenu' => [
                    [
                        'menu' => 'Obat',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Loket',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Laporan Apotek',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Laporan Poliklinik',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Laporan Master Obat',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Laporan Kasir',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                ],
            ],
            [
                'menu' => 'Pengaturan',
                'link' => '#',
                'icon' => 'setting-2',
                'parent' => null,
                'superadmin' => 1,
                'admin_dinas' => 0,
                'admin_faskes' => 1,
                'operator' => 0,
                'dokter' => 0,
                'staff' => 0,
                'pasien' => 0,
                'resepsionis' => 0,
                'apoteker' => 0,
                'kasir' => 0,
                'perawat' => 0,
                'submenu' => [
                    [
                        'menu' => 'Umum',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Lanjut',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Wilayah Kerja',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Tindakan Pendaftaran',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Laborat Pendaftaran',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Bridging BPJS',
                        'link' => 'pengaturan/bpjs',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Bridging Satu Sehat',
                        'link' => 'pengaturan/satu-sehat',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                    [
                        'menu' => 'Grup',
                        'link' => '#',
                        'icon' => null,
                        'parent' => null,
                        'superadmin' => 1,
                        'admin_dinas' => 0,
                        'admin_faskes' => 1,
                        'operator' => 0,
                        'dokter' => 0,
                        'staff' => 0,
                        'pasien' => 0,
                        'resepsionis' => 0,
                        'apoteker' => 0,
                        'kasir' => 0,
                        'perawat' => 0
                    ],
                ],
            ]
        ];

        // Simpan data menu ke tabel 'roles' dalam database
        $this->saveMenu($menu, null);
    }

    private function saveMenu($menu, $parentId)
    {
        foreach ($menu as $item) {
            // Simpan setiap item menu ke tabel 'roles'
            $role = \App\Models\MasterData\Role\Role::create([
                'menu' => $item['menu'],
                'link' => $item['link'],
                'icon' => $item['icon'],
                'parent' => $parentId,
                'superadmin' => $item['superadmin'],
                'admin_dinas' => $item['admin_dinas'],
                'admin_faskes' => $item['admin_faskes'],
                'operator' => $item['operator'],
                'dokter' => $item['dokter'],
                'staff' => $item['staff'],
                'pasien' => $item['pasien'],
                'resepsionis' => $item['resepsionis'],
                'apoteker' => $item['apoteker'],
                'kasir' => $item['kasir'],
                'perawat' => $item['perawat']
            ]);

            // Jika ada submenu, panggil rekursif
            if (isset($item['submenu'])) {
                $this->saveMenu($item['submenu'], $role->uuid_role);
            }
        }
    }
}
